import { gql } from "@apollo/client";
import Head from "next/head";
import Footer from "../components/footer/Footer";
import Header from "../components/header/Header";
import RelatedPosts from "../components/widgets/relatedPosts/RelatedPosts";
import SinglePost from "../Layouts/singlepost/SinglePost";
import { client } from "../lib/apollo";

export default function Single({ post,relatedPosts }) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <SinglePost post={post}>
        <div dangerouslySetInnerHTML={{ __html: post.content }}></div>
      </SinglePost>
      <RelatedPosts />
      <Footer />
    </div>
  );
}

export async function getStaticPaths() {
  const result = await client.query({
    query: gql`
      query GetPosts {
        posts {
          nodes {
            slug
            categories {
              nodes {
                name
              }
            }
          }
          
        }
      }
    `,
  });
  console.log(result)
  return {
    paths: result.data.posts.nodes.map(({ slug }) => {
      return {
        params: { slug  },
      };
    }),
    fallback: false,
  };
}

export async function getStaticProps({ params }) {
  console.log(params);
  const { slug } = params;
  const result = await client.query({
    query: gql`
      query SinglePostBySlug($slug: String!) {
        postBy(slug: $slug) {
          author {
            node {
              avatar {
                url
              }
              name
            }
          }
          categories {
            nodes {
              name
            }
          }
          featuredImage {
            node {
              sourceUrl(size: CSCO_LARGE)
            }
          }
          modified
          slug
          title
          content
        }
      }
    `,
    variables: { slug },
  });


  return {
    props: {
      post: result.data.postBy,
    },
  };
}
