import { gql } from "@apollo/client";
import Head from "next/head";
import Footer from "../components/footer/Footer";
import Header from "../components/header/Header";
import RelatedPosts from "../components/widgets/relatedPosts/RelatedPosts";
import SinglePost from "../Layouts/singlepost/SinglePost";
import { client } from "../lib/apollo";

export default function Single({ post }) {
  const postsByCategory = post.categories.nodes[0].posts.nodes.slice(0, 4);

  const relatedPosts = postsByCategory.filter((relPost) => relPost.title !== post.title);

  // console.log(relatedPosts);
  return (
    <div>
      <Head>
        <title>{post.title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <SinglePost post={post}>
        <div dangerouslySetInnerHTML={{ __html: post.content }}></div>
      </SinglePost>
      <RelatedPosts relatedPosts= {relatedPosts}  />
      <Footer />
    </div>
  );
}

export async function getStaticPaths() {
  const result = await client.query({
    query: gql`
      query GetPosts {
        posts(first:50) {
          nodes {
            slug
          }
        }
      }
    `,
  });
  return {
    paths: result.data.posts.nodes.map(({ slug }) => {
      return {
        params: { slug },
      };
    }),
    fallback: false,
  };
}

export async function getStaticProps({ params }) {
  const { slug } = params;
  const result = await client.query({
    query: gql`
      query SinglePostBySlug($slug: String!) {
        postBy(slug: $slug) {
          author {
            node {
              avatar {
                url
              }
              name
            }
          }
          categories {
            nodes {
              name
              posts {
                nodes {
                  title
                  slug
                  modified
                  categories {
                    nodes {
                      name
                    }
                  }
                  excerpt
                  author {
                    node {
                      avatar {
                        url
                      }
                      name
                    }
                  }
                  featuredImage {
                    node {
                      sourceUrl(size: CNVS_THUMBNAIL)
                    }
                  }
                }
              }
            }
          }
          featuredImage {
            node {
              sourceUrl(size: CSCO_LARGE)
            }
          }
          modified
          slug
          title
          content
        }
      }
    `,
    variables: { slug },
  });

  return {
    props: {
      post: result.data.postBy,
    },
  };
}
