import Head from "next/head";
import Footer from "../components/footer/Footer";
import Header from "../components/header/Header";
import ListPosts from "../components/listposts/ListPosts";
import FeatGrid from "../components/sections/featGrid/FeatGrid";
import SingleFeat from "../components/sections/singleFeat/singleFeat";
import ThreeColGrid from "../components/sections/threecolgrid/ThreeColGrid";
import RelatedPosts from "../components/widgets/relatedPosts/RelatedPosts";
import SinglePost from "../Layouts/singlepost/SinglePost";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <FeatGrid/>
      <ListPosts/>
      <ThreeColGrid/>
      <Footer/>
    </div>
  );
}
